[package]
name = "ef_tests"
version.workspace = true
edition.workspace = true

[dependencies]
revm = { version = "9.0.0", features = ["serde", "std", "serde-json"] }
ethereum-types = "0.14.1"
serde.workspace = true
serde_json.workspace = true
