[workspace]
members = [
    "ethereum_rust",
    "crates/consensus",
    "crates/core",
    "crates/evm",
    "crates/net",
    "crates/rpc",
    "crates/storage",
]
resolver = "2"

[workspace.package]
name = "ethereum_rust"
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
rpc = { path = "./crates/rpc" }

tracing = "0.1"
tracing-subscriber = "0.3.0"
