[workspace]
members = [
    "crates/consensus",
    "crates/core",
    "crates/net",
    "crates/rpc",
    "crates/storage",
    "cmd/ethereum_rust",
    "cmd/ef_tests",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
ethereum_rust-consensus = { path = "./crates/consensus" }
ethereum_rust-core = { path = "./crates/core" }
ethereum_rust-net = { path = "./crates/net" }
ethereum_rust-rpc = { path = "./crates/rpc" }
ethereum_rust-storage = { path = "./crates/storage" }

tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.3.0"

serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
libmdbx = { version = "0.5.0", features = ["orm"] }
bytes = "1.6.0"
tokio = { version = "1.38.0", features = ["full"] }
thiserror = "1.0.61"
hex = "0.4.3"
lazy_static = "1.5.0"
patricia-merkle-tree = { git = "https://github.com/lambdaclass/merkle_patricia_tree.git" }
sha3 = "0.10.8"
