[workspace]
members = [
    "ethrex",
    "crates/consensus",
    "crates/core",
    "crates/evm",
    "crates/net",
    "crates/rpc",
    "crates/storage",
    "ef_tests",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
rpc = { path = "./crates/rpc" }
core = { path = "./crates/core" }

tracing = "0.1"
tracing-subscriber = "0.3.0"

serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
libmdbx = { version = "0.5.0", features = ["orm"] }
