[package]
name = "ethereum_rust-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethereum_rust-core.workspace = true

ethereum-types = "0.14.1"
anyhow = "1.0.86"
bytes.workspace = true
tracing.workspace = true
thiserror.workspace = true
patricia-merkle-tree.workspace = true
sha3.workspace = true
hex.workspace = true
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
libmdbx = { workspace = true, optional = true }

# trie deps
smallvec = {version = "1.10.0", features = ["const_generics", "union"]}
digest = "0.10.6"
lazy_static.workspace = true

[features]
default = ["in_memory", "libmdbx"]
in_memory = []
libmdbx = ["dep:libmdbx"]

[dev-dependencies]
hex.workspace = true
hex-literal.workspace = true
proptest = "1.0.0"
tempdir = "0.3.7"
cita_trie = "4.0.0" # used for proptest comparisons
hasher = "0.1.4" # cita_trie needs this

[lib]
path = "./storage.rs"
