[package]
name = "ethereum_rust-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethereum_rust-core.workspace = true

ethereum-types = "0.14.1"
libmdbx.workspace = true
anyhow = "1.0.86"
bytes.workspace = true
tracing.workspace = true
thiserror.workspace = true

sled = { version = "0.34.7", optional = true }
rocksdb = { version = "0.19.0", optional = true }

[features]
default = ["in_memory", "libmdbx"]
in_memory = []
libmdbx = []
sled = ["dep:sled"]
rocksdb = ["dep:rocksdb"]