[package]
name = "ethereum_rust-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethereum_rust-core.workspace = true

libmdbx.workspace = true
anyhow = "1.0.86"
patricia-merkle-tree.workspace = true
sha3.workspace = true

[dev-dependencies]
hex.workspace = true
