[package]
name = "ethereum_rust-storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethereum_rust-core.workspace = true

ethereum-types = "0.14.1"
anyhow = "1.0.86"
bytes.workspace = true
tracing.workspace = true
thiserror.workspace = true
patricia-merkle-tree.workspace = true
sha3.workspace = true

libmdbx = { workspace = true, optional = true }
sled = { version = "0.34.7", optional = true }
rocksdb = { version = "0.19.0", optional = true }

[features]
default = ["in_memory", "libmdbx"]
in_memory = []
libmdbx = ["dep:libmdbx"]
sled = ["dep:sled"]
rocksdb = ["dep:rocksdb"]

[dev-dependencies]
hex.workspace = true

[lib]
path = "./storage.rs"
