[package]
version = "0.1.0"
name = "zkVM-program"
edition = "2021"

[workspace]

[dependencies]
alloy-sol-types = "0.7.7"
sp1-zkvm = "2.0.0"
lib = { path = "../lib" }

# TODO We need the patch_000_mdbx branch, check how to reference the repo directly (merge the branch?).
# ethereum_rust
ethereum_rust-core = { git = "https://github.com/lambdaclass/ethereum_rust", package = "ethereum_rust-core", branch = "patch_000_mdbx", default-features = false, features = [
    "no_libmdbx",
] }
ethereum_rust-blockchain = { git = "https://github.com/lambdaclass/ethereum_rust", package = "ethereum_rust-blockchain", branch = "patch_000_mdbx", default-features = false, features = [
    "no_libmdbx",
] }
ethereum_rust-evm = { git = "https://github.com/lambdaclass/ethereum_rust", package = "ethereum_rust-evm", branch = "patch_000_mdbx", default-features = false, features = [
    "no_libmdbx",
] }
ethereum_rust-storage = { git = "https://github.com/lambdaclass/ethereum_rust", package = "ethereum_rust-storage", branch = "patch_000_mdbx", default-features = false, features = [
    "no_libmdbx",
] }

# revm
revm = { version = "14.0.3", features = [
    "std",
    "serde",
    "kzg-rs",
], default-features = false }

# reth
# This should be a custom error
reth-storage-errors = { git = "https://github.com/paradigmxyz/reth", default-features = false, features = [
    "std",
] }
