[package]
name = "ethereum_rust-blockchain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror.workspace = true
ethereum_rust-rlp.workspace = true
sha3.workspace = true
tracing.workspace = true

ethereum_rust-core = { path = "../common", default-features = false }
ethereum_rust-storage = { path = "../storage/store", default-features = false }
ethereum_rust-vm = { path = "../vm", default-features = false }

bytes.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lib]
path = "./blockchain.rs"

[features]
default = ["libmdbx"]
libmdbx = [
    "ethereum_rust-core/libmdbx",
    "ethereum_rust-storage/libmdbx",
    "ethereum_rust-vm/libmdbx",
]
