[package]
name = "core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.6.0"
tinyvec = "1.6.0"
ethereum-types = "0.14.1"
serde.workspace = true

[dev-dependencies]
hex-literal = "0.4.1"
