name: Hive
on:
  merge_group:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  RUST_VERSION: 1.80.1
  HIVE_TEST_PATTERN: "/eth_chainId|eth_blockNumber"

jobs:
  run-hive:
    name: Run Hive
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Rustup toolchain install
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Setup just
        uses: extractions/setup-just@v2
      
      - name: Setup Go
        uses: actions/setup-go@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Download Hive
        run: just setup-hive

      - name: Run Hive
        run: just run-hive
